[package]
name = "server_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
cargo-watch = "8.5.2"
serde = { version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1.0"
